Update TJSON.hx
Not sure why this fails, but this change fixed my `TypeError`

I ran into the error using Haxelow (which uses TJSON) with the Python target

```
    buffer_b.write(Std.string((((("\"" + ("null" if field is None else field)) + "\"") + Std.string(style.keyValueSeperator(depth))) + ("null" if vStr is None else vStr))))
TypeError: Can't convert 'int' object to str implicitly
```

Example code here: https://github.com/MatthijsKamstra/haxepython/blob/master/04haxelow/code/src/Main.hx